version: '3.8'

services:
  # Deshabilitar servicios no esenciales para desarrollo local
  elasticsearch:
    profiles:
      - elasticsearch
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  kibana:
    profiles:
      - elasticsearch

  redis-commander:
    profiles:
      - redis-commander

  adminer:
    profiles:
      - adminer

  smtp-server:
    profiles:
      - smtp

  selenium-server:
    profiles:
      - selenium

  img-proxy:
    profiles:
      - img-proxy

  # Optimizar servicios esenciales
  php-fpm:
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  postgres:
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  redis:
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  rabbitmq:
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  storefront:
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  webserver:
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
