version: '3.8'

services:
  # Solo servicios esenciales para desarrollo local
  postgres:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: shopsys
      POSTGRES_USER: shopsys
      POSTGRES_PASSWORD: shopsys
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    environment:
      - UID=1000
      - GID=1000
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  webserver:
    image: nginx:1.27-alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
    depends_on:
      - php-fpm
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M

volumes:
  postgres_data:
