version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine
    container_name: shopsys-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=shopsys
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c max_connections=50

  redis:
    image: redis:7.4-alpine
    container_name: shopsys-redis
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru

  php-fpm:
    build:
      context: ./project-base/app
      dockerfile: docker/php-fpm/Dockerfile
      target: development
      args:
        www_data_uid: 1000
        www_data_gid: 1000
    container_name: shopsys-php-fpm
    volumes:
      - ./project-base/app:/var/www/html
    environment:
      - LOCAL_PATH_TO_PROJECT_ROOT=/var/www/html
    depends_on:
      - postgres
      - redis
    ports:
      - "9000:9000"

  webserver:
    image: nginx:1.27-alpine
    container_name: shopsys-webserver
    depends_on:
      - php-fpm
    volumes:
      - ./project-base/app:/var/www/html
      - ./nginx-minimal.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:8080"

  storefront:
    build:
      context: ./project-base/storefront
      dockerfile: ./docker/dev.Dockerfile
      target: development
      args:
        node_uid: 1000
    container_name: shopsys-storefront
    command: dev
    volumes:
      - ./project-base/storefront:/home/node/app
    ports:
      - "3000:3000"
    environment:
      - NODE_OPTIONS=--max-old-space-size=1024

volumes:
  postgres-data:
    driver: local
