Query:
    type: object
    inherits:
        - 'QueryDecorator'
        - 'CategoryQuery'
        - 'SliderQuery'
        - 'OrderQuery'
        - 'ProductQuery'
        - 'SeoPageQuery'
        - 'RecommendationQueryDecorator'
