security:
    # This is only placeholder for the role hierarchy as Hierarchy is created dynamically
    role_hierarchy:
        PUBLIC_ACCESS: []
    access_control:
        # Two-factor authentication routes
        - { path: ^/%admin_url%/logout, roles: PUBLIC_ACCESS }
        - { path: ^/%admin_url%/2fa, roles: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/%admin_url%/$, roles: PUBLIC_ACCESS }

        # File manager access
        - { path: ^/efconnect, roles: ROLE_ADMIN }
        - { path: ^/elfinder, roles: ROLE_ADMIN }
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\UserInterface:
            algorithm: bcrypt
            cost: 12

    providers:
        administrators:
            id: Shopsys\FrameworkBundle\Model\Administrator\Security\AdministratorUserProvider

        user_identities:
            id: Shopsys\FrameworkBundle\Model\Customer\User\FrontendCustomerUserProvider

        frontend_api_user_identities:
            id: Shopsys\FrontendApiBundle\Model\User\FrontendApiUserProvider

    firewalls:
        # see Shopsys\FrameworkBundle\Model\Administrator\Security\AdministratorFrontSecurityFacade
        administration:
            pattern: ^/(%admin_url%/|efconnect|elfinder)
            user_checker: Shopsys\FrameworkBundle\Model\Security\AdministratorChecker
            provider: administrators
            access_denied_handler: Shopsys\AdministrationBundle\Component\Security\AccessDeniedHandler
            entry_point: form_login
            login_throttling:
                max_attempts: 5
                interval: '1 minute'
            form_login:
                check_path: admin_login_check
                login_path: admin_login
                default_target_path: admin_default_dashboard
                use_referer: true
                username_parameter: "admin_login_form[username]"
                password_parameter: "admin_login_form[password]"
                csrf_parameter: "admin_login_form[_token]"
            logout:
                path: admin_logout
                csrf_parameter: _csrf_token
                csrf_token_generator: security.csrf.token_manager
                csrf_token_id: admin_logout
                invalidate_session: false
            two_factor:
                auth_form_path: 2fa_login    # The route name you have used in the routes.yaml
                check_path: 2fa_login_check  # The route name you have used in the routes.yaml
        frontend_api:
            pattern: ^/(graphql|customer-file)
            provider: frontend_api_user_identities
            stateless: true
            login_throttling:
                max_attempts: 5
                interval: '1 minute'
            custom_authenticators:
                - App\FrontendApi\Model\Token\TokenAuthenticator
