ux_icons:
    aliases:
        arrow: 'tabler:caret-down-filled'
        arrow-back: 'tabler:arrow-back'
        arrow-down: 'tabler:arrow-big-down-filled'
        arrow-left: 'tabler:arrow-big-left-filled'
        arrow-right: 'tabler:arrow-big-right-filled'
        arrow-simple: 'tabler:arrow-right'
        arrow-strong: 'tabler:chevron-right'
        arrow-thin: 'tabler:chevron-compact-right'
        arrow-up: 'tabler:arrow-big-up-filled'
        calendar-3: 'tabler:calendar-week'
        cart: 'tabler:basket-filled'
        chart-piece: 'tabler:clipboard-data-filled'
        checked: 'tabler:check'
        checked-circle: 'tabler:circle-check'
        circle-cross: 'tabler:xbox-x-filled'
        circle-plus: 'tabler:circle-plus'
        circle-remove: 'tabler:circle-minus'
        company: 'tabler:building'
        delete: 'tabler:x'
        delete-thin: 'tabler:x'
        document-copy: 'tabler:clipboard-text-filled'
        double-arrow: 'tabler:chevrons-left'
        download: 'tabler:download'
        duplicate: 'tabler:copy'
        file-all: 'tabler:file-text'
        file-excel: 'tabler:file-type-xls'
        file-image: 'tabler:photo'
        file-not-found: 'tabler:file-sad'
        file-pdf: 'tabler:file-type-pdf'
        file-word: 'tabler:file-type-doc'
        file-xml: 'tabler:file-type-xml'
        filter: 'tabler:filter-filled'
        flag: 'tabler:flag-3-filled'
        folder: 'tabler:folder-filled'
        forward-page: 'tabler:external-link'
        gear: 'tabler:settings-filled'
        house: 'tabler:home-filled'
        info: 'tabler:info-circle-filled'
        invisible: 'tabler:eye-off'
        letter: 'tabler:mail-filled'
        light-bulb: 'tabler:bulb-filled'
        menu: 'tabler:menu-2'
        minus: 'tabler:minus'
        move: 'tabler:arrows-move'
        pencil: 'tabler:edit'
        person-door-man: 'tabler:user-square'
        person-man: 'tabler:user'
        person-public: 'tabler:users'
        phone: 'tabler:phone'
        power: 'tabler:power'
        print: 'tabler:printer'
        puzzle: 'tabler:puzzle-filled'
        question: 'tabler:question-mark'
        schedule: 'tabler:clock-filled'
        search: 'tabler:search'
        select-all: 'tabler:select-all'
        support: 'tabler:headset'
        tag: 'tabler:tag-filled'
        trash: 'tabler:trash-x-filled'
        unselect-all: 'tabler:deselect'
        upload: 'tabler:upload'
        user: 'tabler:user-circle'
        visible: 'tabler:eye'
        warning: 'tabler:alert-triangle'
    default_icon_attributes:
        fill: currentColor
        height: 20
        width: 20
